# lambda pa / lambda_pi / batch /  
#
student_model:
    student: kd_senet_stage3_fpn14_b111
    backbone: resnet18

teacher_model:
    teacher: fanet_se_stdc1
    backbone: stdc1

data:
    dataset: lpcvc 
    train_split: train  
    val_split: val
    img_rows: 512
    img_cols: 512
    path: 

training:
    n_workers: 2
    train_iters: 40000
    batch_size: 128
    val_interval: 500
    print_interval: 50

    # hyperparam
    lambda_pa : 0.2
    lambda_pi : 10.0
    
    sg_loss:
        name: OhemCELoss2D 
        thresh: 0.7
        ignore_index: 250
    pi_loss: 
        name: CriterionPixelWise 
    pa_loss: 
        name: CriterionPairWiseforWholeFeatAfterPool 

    # teacher model pretrained 필요
    student_resume: 
    teacher_resume: 

    s_optimizer:
        name: adaoptimizer
        momentum: 0.9
        lr_multi: 1
        bn_wd_disable: False
        wd: 5.0e-4
        lr0: 1.0e-3
        max_iter: 40000
        power: 0.9
        warmup_steps: 1000
        warmup_start_lr: 1.0e-5

    train_augmentations:
        rotate: 5
        brightness: 0.5
        contrast: 0.5
        saturation: 0.5
        scale: [512,512]
        rscale: [0.5,2]
        hflip: 0.5
        rcrop: [384,384]
        norm: 255.0
        cnorm : [[0.46074432, 0.45581704, 0.4192581],[0.18550818, 0.17077453, 0.1769904]]
    visdom: False

validating:
    densecrf: False
    resume:
    n_workers: 1
    batch_size: 1
    outpath: 
    val_augmentations:
        scale: [512,512]
        norm: 255.0
        cnorm : [[0.46074432, 0.45581704, 0.4192581],[0.18550818, 0.17077453, 0.1769904]]